# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6bc3b7c1aeec1601ab2c592d98248c29df66ec7d9150539a5150cee8e6e32bec1c2347fdb6e27b019cd4864c8692e92982a15c1b7e5c7a11b12b3d2ee68c89a

test:
  secret_key_base: 10b89cad3920750dc664fdcdcf2d17cb68ae4d4f05f5fd5b6197a7c1f3b5929f5fe3f36edf16f163e557a372a9e41be89e533dc7b3ab687b42754f7b82f75904

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
